# Generated by Django 5.2.5 on 2025-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('user_descriptn', models.TextField()),
                ('spices', models.TextField(blank=True)),
                ('vegetables', models.TextField(blank=True)),
                ('cheese', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Order Received'), ('making', 'Being prepared'), ('baking', 'Baking'), ('shipping', 'Out for delivery'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('chef_assigned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
