# Generated by Django 5.2.5 on 2025-11-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='cheese',
            new_name='ingrednts',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='spices',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='vegetables',
        ),
    ]
